[package]
name = "okizeme_offense"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
bevy = "0.7"
bevy-inspector-egui = { version = "0.8", optional = true }
serde_json = "1.0"
serde = "1.0.136"

okizeme_defense = {path = "../okizeme_defense", version="0.1.0"}
okizeme_types = {path = "../okizeme_types", version="0.1.0"}
okizeme_utils = {path = "../okizeme_utils", version="0.1.0"}
