[package]
name = "okizeme_core"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
okizeme_input = {path = "../okizeme_input"}
okizeme_player = {path = "../okizeme_player"}
okizeme_animation = {path = "../okizeme_animation"}
okizeme_offense = {path = "../okizeme_offense"}
okizeme_defense = {path = "../okizeme_defense"}
okizeme_utils = {path = "../okizeme_utils"}
okizeme_types = {path = "../okizeme_types"}
