use crate::*;

#[derive(Debug)]
/// Event generated by each input device each frame to read player inputs
pub struct InputEvent {
    pub player_id: PlayerId,
    pub input_mask: InputMask,
}

impl InputEvent {
    pub fn new(player_id: PlayerId, input_mask: InputMask) -> Self {
        InputEvent {
            player_id,
            input_mask,
        }
    }
}
